config/routes.rb
Rails.application.routes.draw do

   root 'static_pages#root'

   resource :session, only: [:new, :create, :destroy]
   resources :users, only: [:new, :create]

   delete 'api/shelving' => "api/shelvings#destroy_by_ids"
   namespace :api, defaults: {format: :json} do
     resources :users, only: [:show]
     resources :ratings, only: [:create, :update, :destroy, :show]
     resources :reviews, only: [:create, :update, :destroy, :show]
     resources :shelvings, only: [:create, :destroy, :show]
     get 'games/explore' => 'games#explore'
     resources :games, only: [:show, :index, :update] do
       get 'page/:page', :action => :index, :on => :collection
     end
     resources :shelves, only: [:show, :index, :update, :create] do
       resources :games, only: [:index]
     end
   end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  after_initialize :ensure_session_token

  has_many :shelves, dependent: :destroy, inverse_of: :user
  has_many :games, through: :shelves
  has_many :reviews, dependent: :destroy, inverse_of: :user
  has_many :ratings, dependent: :destroy, inverse_of: :user

  attr_reader :password
  validates :password, length: {minimum: 6, allow_nil: true }

  def self.find_by_credentials(email, password)
    cand = self.find_by_email(email)
    if cand and cand.is_password?(password)
      return cand
    else
      return nil
    end
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def self.new_guest
    return User.find(1);
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    save!
    session_token
  end

  def password=(plaintext_password)
    self.password_digest = BCrypt::Password.create(plaintext_password)
    @password = plaintext_password
  end

  def is_password?(plaintext_password)
    password_digest.is_password?(plaintext_password)
  end

  def password_digest
    BCrypt::Password.new(super)
  end

  def guest?
    false
  end

  private
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  before_action :require_logged_in

  def show
    @user = User.find(params[:id])
    render :show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_out, only: [:new, :create]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = params[:user] ? User.new(user_params) : User.new_guest
    if @user.save
      login_user!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :session_token)
  end
end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="sign-in col-sm-6 col-md-4 col-lg-2 col-lg-offset-1">
  <div class="row">
    <h1>Welcome to SideTable</h1>
    <h4>The board game site for social gamers</h4>
  </div>
  <div class="row">
    <h2>Sign Up</h2>
    <%= form_for :user, url: {controller: :users, action: :create},
      html: { class: "form-horizontal login-form"  } do |f| %>
      <label class="sr-only" for="email-field">Email</label>
      <%= f.text_field :email, class: "form-control", 
        placeholder: "Email", id: "email-field" %>
      <label class="control-label sr-only" for="password-field">Password</label>
      <%= f.password_field :password, class: "form-control col-sm-10",
        placeholder: "Password", id: "password-field" %>
      <%= f.submit "Sign Up", class: "btn btn-primary col-xs-12" %>
   <% end %>
   <%= button_to "Guest Login", users_path, method: :post, 
     class: "btn btn-info col-xs-12", form_class: "login-form" %>
   <%= link_to "Login", new_session_path,
     class: "btn btn-default col-xs-12", form_class: "login-form"  %>
  </div>
</div>
<div class="col-sm-6 col-md-8 col-lg-8" id="content">
</div>
<script type="text/javascript">
  CurrentUser = {};
  <% if current_user %>
    CurrentUser.email = "<%= current_user.email %>";
    CurrentUser.id = "<%= current_user.id %>";
    CurrentUser.name = "<%= current_user.name %>";
  <% end %>
</script>